// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifucntxbljymzepxhghx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmdWNudHhibGp5bXplcHhoZ2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzE1ODEsImV4cCI6MjA2MTY0NzU4MX0.ZZIT-x3vO08-K34zzju1DcmErLdChPNt2Ugb0hHTpFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);